# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

# Install any needed dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application's source code
COPY . .

# Build the TypeScript project
RUN npm run build

# Use a smaller Node.js runtime for production
FROM node:18-alpine AS release

# Set the working directory in the container
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/build /app/build

# Copy package.json and package-lock.json for production installation
COPY --from=builder /app/package.json /app/package-lock.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Define environment variable for the Replicate API token
ENV REPLICATE_API_TOKEN=your_token_here

# Run the MCP server
CMD ["node", "build/index.js"]